server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  redis:
    host: 192.168.107.129
  rabbitmq:
    host: 192.168.107.129
    virtual-host: /vh
    username: wuhao
    password: 123456
    publisher-confirm-type: CORRELATED
    publisher-returns: true
  thymeleaf:
    cache: false
feign:
  sentinel:
    enabled: true
logging:
  level:
    com.atguigu.gmall: debug

