server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  thymeleaf:
    cache: false
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
feign:
  sentinel:
    enabled: true
auth:
  jwt:
    pubKeyPath: D:\test\project\rsa\rsa.pub
    priKeyPath: D:\test\project\rsa\rsa.pri
    secret: SIUUuuii*&*&&*
    cookieName: GMALL-TOKEN
    expire: 180
    nickName: unick
